In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 3.1800e-20,  4.5622e-41, -9.7912e-31],
        [ 3.0691e-41, -2.8925e+25,  4.5621e-41],
        [-2.8925e+25,  4.5621e-41, -2.9502e+25],
        [ 4.5621e-41, -2.8925e+25,  4.5621e-41],
        [-2.9503e+25,  4.5621e-41, -2.8978e+25]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.9776,  0.5978,  0.1528],
        [ 0.8383,  0.1104,  0.9119],
        [ 0.6509,  0.0449,  0.1080],
        [ 0.3938,  0.0015,  0.6361],
        [ 0.0857,  0.2397,  0.3167]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.6146, -0.1493, -1.0484],
        [-1.1778,  0.5716, -0.9121],
        [ 0.2381,  0.6277,  0.4220],
        [ 0.6767,  1.1845,  0.6465],
        [-1.1355,  2.0349,  0.4327]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.5606, -0.1113, -0.2712],
        [-0.8527,  1.0352, -0.3310],
        [ 0.5990,  1.0508,  1.4209],
        [ 0.9556,  1.5246,  0.8356],
        [-0.1730,  2.4356,  0.9139]])


In [12]:
print(torch.add(x, y))

tensor([[ 1.5606, -0.1113, -0.2712],
        [-0.8527,  1.0352, -0.3310],
        [ 0.5990,  1.0508,  1.4209],
        [ 0.9556,  1.5246,  0.8356],
        [-0.1730,  2.4356,  0.9139]])


In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.5606, -0.1113, -0.2712],
        [-0.8527,  1.0352, -0.3310],
        [ 0.5990,  1.0508,  1.4209],
        [ 0.9556,  1.5246,  0.8356],
        [-0.1730,  2.4356,  0.9139]])


In [14]:
y.add_(x)
print(y)

tensor([[ 1.5606, -0.1113, -0.2712],
        [-0.8527,  1.0352, -0.3310],
        [ 0.5990,  1.0508,  1.4209],
        [ 0.9556,  1.5246,  0.8356],
        [-0.1730,  2.4356,  0.9139]])


In [15]:
print(x[:, 1])

tensor([-0.1493,  0.5716,  0.6277,  1.1845,  2.0349])


In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor(1.00000e-03 *
       [-9.5228])
-0.00952279381453991


In [19]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [20]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [21]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[ 2.  2.  2.  2.  2.]


In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)
