In [ ]:
import tensorflow as tf
a = tf.constant([1.0, 2.0])
b = tf.constant([3.0, 4.0])
result = a + b
print(result)

In [ ]:
x = tf.constant([[1.0, 2.0]])
w = tf.constant([[3.0], [4.0]])
y = tf.matmul(x, w)
print(y)

In [ ]:
with tf.Session() as sess:
    print(sess.run(y))

In [ ]:
x = tf.placeholder(tf.float32, shape=(None, 2))
w1 = tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1))
w2 = tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1))

a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    print("y is :\n", sess.run(y, feed_dict={x:[[0.7, 0.5], 
                                                [0.2, 0.3],
                                                [0.3, 0.4],
                                                [0.4, 0.5]]}))

In [ ]:
x = tf.placeholder(tf.float32, shape=(1, 2))
w1 = tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1))
w2 = tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1))

a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    print("y is :\n", sess.run(y, feed_dict={x:[[0.7, 0.5]]}))

In [ ]:
import tensorflow as tf
import numpy as np
BATCH_SIZE = 8
SEED = 23455

#基于seed产生随机数
rdm = np.random.RandomState(SEED)
#随机数返回32行2列的矩阵 表示32组 体积和重量 作为输入数据集
X = rdm.rand(32,2)
#从X这个32行2列的矩阵中 取出一行 判断如果和小于1 给Y赋值1 如果和不小于1 给Y赋值0 
#作为输入数据集的标签（正确答案） 
Y_ = [[int(x0 + x1 < 1)] for (x0, x1) in X]
print ("X:\n",X)
print ("Y_:\n",Y_)

#1定义神经网络的输入、参数和输出,定义前向传播过程。
x = tf.placeholder(tf.float32, shape=(None, 2))
y_= tf.placeholder(tf.float32, shape=(None, 1))

w1= tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1))
w2= tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1))

a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

#2定义损失函数及反向传播方法。
loss_mse = tf.reduce_mean(tf.square(y-y_)) 
train_step = tf.train.GradientDescentOptimizer(0.001).minimize(loss_mse)
#train_step = tf.train.MomentumOptimizer(0.001,0.9).minimize(loss_mse)
#train_step = tf.train.AdamOptimizer(0.001).minimize(loss_mse)

#3生成会话，训练STEPS轮
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    # 输出目前（未经训练）的参数取值。
    print ("w1:\n", sess.run(w1))
    print ("w2:\n", sess.run(w2))
    print ("\n")
    
    # 训练模型。
    STEPS = 3000
    for i in range(STEPS):
        start = (i*BATCH_SIZE) % 32
        end = start + BATCH_SIZE
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y_[start:end]})
        if i % 500 == 0:
            total_loss = sess.run(loss_mse, feed_dict={x: X, y_: Y_})
            print("After %d training step(s), loss_mse on all data is %g" % (i, total_loss))
    
    # 输出训练后的参数取值。
    print ("\n")
    print ("w1:\n", sess.run(w1))
    print ("w2:\n", sess.run(w2))

In [ ]:
import tensorflow as tf
import numpy as np

BATCH_SIZE = 8
seed = 23455

rng = np.random.RandomState(seed)
X = rng.rand(32, 2)
Y = [[int(x0 + x1 < 1) for (x0, x1) in X]]
print("X:\n", X)
print("Y:\n", Y)

In [3]:
import tensorflow as tf
import numpy as np
BATCH_SIZE = 8
SEED = 23455

rdm = np.random.RandomState(SEED)
X = rdm.rand(32, 2)
Y_ = [[x1+x2+(rdm.rand()/10.0-0.05)] for (x1, x2) in X]

x = tf.placeholder(tf.float32, shape=(None, 2))
y_ = tf.placeholder(tf.float32, shape=(None, 1))
w1 = tf.Variable(tf.random_normal([2, 1], stddev=1, seed=1))
y = tf.matmul(x, w1)

loss_mse = tf.reduce_mean(tf.square(y_ - y))
train_step = tf.train.GradientDescentOptimizer(0.001).minimize(loss_mse)

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    Steps = 20000
    for i in range(Steps):
        start = (i*BATCH_SIZE) % 32
        end = (i*BATCH_SIZE) % 32 + BATCH_SIZE
        sess.run(train_step, feed_dict={x: X[start: end], y_: Y_[start: end]})
        if i % 500 == 0:
            print("After {} training steps, w1 is: ".format (i))
            print(sess.run(w1), "\n")
    print("Final w1 is: \n", sess.run(w1))

After 0 training steps, w1 is: 
[[-0.80974597]
 [ 1.4852903 ]] 

After 500 training steps, w1 is: 
[[-0.46074435]
 [ 1.641878  ]] 

After 1000 training steps, w1 is: 
[[-0.21939856]
 [ 1.6984766 ]] 

After 1500 training steps, w1 is: 
[[-0.04415595]
 [ 1.7003176 ]] 

After 2000 training steps, w1 is: 
[[0.08942621]
 [1.673328  ]] 

After 2500 training steps, w1 is: 
[[0.19583553]
 [1.6322677 ]] 

After 3000 training steps, w1 is: 
[[0.28375748]
 [1.5854434 ]] 

After 3500 training steps, w1 is: 
[[0.35848638]
 [1.5374471 ]] 

After 4000 training steps, w1 is: 
[[0.4233252]
 [1.4907392]] 

After 4500 training steps, w1 is: 
[[0.48040032]
 [1.4465573 ]] 

After 5000 training steps, w1 is: 
[[0.5311361]
 [1.4054534]] 

After 5500 training steps, w1 is: 
[[0.57653254]
 [1.367594  ]] 

After 6000 training steps, w1 is: 
[[0.6173259]
 [1.3329402]] 

After 6500 training steps, w1 is: 
[[0.65408474]
 [1.3013425 ]] 

After 7000 training steps, w1 is: 
[[0.68726856]
 [1.2726018 ]] 

After 7500 t

In [7]:
import tensorflow as tf
import numpy as np
BATCH_SIZE = 8
SEED = 23455
COST = 1
PROFIT = 9

rdm = np.random.RandomState(SEED)
X = rdm.rand(32, 2)
Y = [[x1 + x2 + rdm.rand()/10.0-0.05] for (x1, x2) in X]

x = tf.placeholder(tf.float32, shape=(None, 2))
y_ = tf.placeholder(tf.float32, shape=(None, 1))
w1 = tf.Variable(tf.random_normal([2, 1], stddev=1, seed=1))
y = tf.matmul(x, w1)

loss = tf.reduce_sum(tf.where(tf.greater(y, y_), (y - y_) * COST, (y_ - y) * PROFIT))
train_step = tf.train.GradientDescentOptimizer(0.001).minimize(loss)

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    Steps = 20000
    for i in range(Steps):
        start = (i*BATCH_SIZE) % 32
        end = (i*BATCH_SIZE) % 32 + BATCH_SIZE
        sess.run(train_step, feed_dict={x: X[start: end], y_: Y_[start: end]})
        if i % 500 == 0:
            print("After {} training steps, w1 is: ".format (i))
            print(sess.run(w1), "\n")
    print("Final w1 is: \n", sess.run(w1))

After 0 training steps, w1 is: 
[[-0.762993 ]
 [ 1.5095658]] 

After 500 training steps, w1 is: 
[[1.0235443]
 [1.0463371]] 

After 1000 training steps, w1 is: 
[[1.0174844]
 [1.0406414]] 

After 1500 training steps, w1 is: 
[[1.0211805]
 [1.0472372]] 

After 2000 training steps, w1 is: 
[[1.0179386]
 [1.041272 ]] 

After 2500 training steps, w1 is: 
[[1.0205938]
 [1.0390443]] 

After 3000 training steps, w1 is: 
[[1.0242898]
 [1.04564  ]] 

After 3500 training steps, w1 is: 
[[1.01823  ]
 [1.0399443]] 

After 4000 training steps, w1 is: 
[[1.021926]
 [1.04654 ]] 

After 4500 training steps, w1 is: 
[[1.0245812]
 [1.0443122]] 

After 5000 training steps, w1 is: 
[[1.0195622]
 [1.04744  ]] 

After 5500 training steps, w1 is: 
[[1.0222174]
 [1.0452123]] 

After 6000 training steps, w1 is: 
[[1.0161575]
 [1.0395166]] 

After 6500 training steps, w1 is: 
[[1.0198536]
 [1.0461123]] 

After 7000 training steps, w1 is: 
[[1.0169773]
 [1.0424668]] 

After 7500 training steps, w1 is: 
[[1.01748

In [21]:
import tensorflow as tf

w = tf.Variable(tf.constant(5, dtype=tf.float32))

loss = tf.square(w + 1)

train_step = tf.train.GradientDescentOptimizer(0.0001).minimize(loss)

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    for i in range(40):
        sess.run(train_step)
        w_val = sess.run(w)
        loss_val = sess.run(loss)
        print("After {} steps: w is {},    loss is {}".format(i, w_val, loss_val))

After 0 steps: w is 4.998799800872803,    loss is 35.985599517822266
After 1 steps: w is 4.997600078582764,    loss is 35.97120666503906
After 2 steps: w is 4.996400356292725,    loss is 35.956817626953125
After 3 steps: w is 4.995201110839844,    loss is 35.94243621826172
After 4 steps: w is 4.994001865386963,    loss is 35.92805862426758
After 5 steps: w is 4.99280309677124,    loss is 35.91368865966797
After 6 steps: w is 4.991604328155518,    loss is 35.899322509765625
After 7 steps: w is 4.990406036376953,    loss is 35.88496398925781
After 8 steps: w is 4.989207744598389,    loss is 35.870609283447266
After 9 steps: w is 4.988009929656982,    loss is 35.85626220703125
After 10 steps: w is 4.986812114715576,    loss is 35.8419189453125
After 11 steps: w is 4.985614776611328,    loss is 35.82758331298828
After 12 steps: w is 4.98441743850708,    loss is 35.81325149536133
After 13 steps: w is 4.98322057723999,    loss is 35.798927307128906
After 14 steps: w is 4.9820237159729,    lo