# This is an introduction to Numpy 

In [1]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [2]:
type(a)

numpy.ndarray

In [3]:
a.dtype

dtype('int64')

In [4]:
a.ndim

1

In [5]:
a.size

3

In [6]:
a.shape

(3,)

In [7]:
b = np.array([[1.2, 2.4], [0.3, 4.1]])
b.dtype

dtype('float64')

In [8]:
b.ndim

2

In [9]:
b.size

4

In [10]:
b.shape

(2, 2)

In [11]:
b.itemsize

8

In [12]:
b.data

In [13]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
d = np.array(((1, 2, 3), (4, 5, 6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
e = np.array([(1, 2, 3) , (4, 5, 6), (7, 8, 9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
g = np.array([["a", "b"], ["c", "d"]])
g

array([['a', 'b'],
       ['c', 'd']],
      dtype='<U1')

In [17]:
g.dtype

dtype('<U1')

In [18]:
g.dtype.name

'str32'

In [19]:
f = np.array([[1, 2, 3], [4, 5, 6]], dtype=complex)
f

array([[ 1.+0.j,  2.+0.j,  3.+0.j],
       [ 4.+0.j,  5.+0.j,  6.+0.j]])

In [20]:
np.zeros((3, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [21]:
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [22]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0, 12, 3)

array([0, 3, 6, 9])

In [25]:
np.arange(0, 6, .6)

array([ 0. ,  0.6,  1.2,  1.8,  2.4,  3. ,  3.6,  4.2,  4.8,  5.4])

In [26]:
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
np.linspace(0, 10, 5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [28]:
np.random.random(3)

array([ 0.34603221,  0.73272061,  0.61313138])

In [29]:
np.random.random((3, 3))

array([[ 0.03874404,  0.20969759,  0.0511264 ],
       [ 0.91948885,  0.71915376,  0.00702514],
       [ 0.7553547 ,  0.10448077,  0.3177791 ]])

In [30]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [31]:
a + 4

array([4, 5, 6, 7])

In [32]:
a * 2

array([0, 2, 4, 6])

In [33]:
b = np.arange(4, 8)
b

array([4, 5, 6, 7])

In [34]:
a + b

array([ 4,  6,  8, 10])

In [35]:
a - b

array([-4, -4, -4, -4])

In [36]:
a * b

array([ 0,  5, 12, 21])

In [37]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [38]:
a * np.sqrt(b)

array([ 0.        ,  2.23606798,  4.89897949,  7.93725393])

In [39]:
A = np.arange(0, 9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
B = np.ones((3, 3))
B

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [41]:
A * B

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [42]:
np.dot(A, B)

array([[  3.,   3.,   3.],
       [ 12.,  12.,  12.],
       [ 21.,  21.,  21.]])

In [43]:
A.dot(B)

array([[  3.,   3.,   3.],
       [ 12.,  12.,  12.],
       [ 21.,  21.,  21.]])

In [44]:
np.dot(B, A)

array([[  9.,  12.,  15.],
       [  9.,  12.,  15.],
       [  9.,  12.,  15.]])

In [45]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [46]:
a += 1
a

array([1, 2, 3, 4])

In [47]:
a -= 1
a

array([0, 1, 2, 3])

In [48]:
a += 4
a

array([4, 5, 6, 7])

In [49]:
a *= 2
a

array([ 8, 10, 12, 14])

In [50]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [51]:
np.sqrt(a)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ])

In [52]:
np.log(a)

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436])

In [53]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [54]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
a.sum()

15.0

In [55]:
a.min()

0.29999999999999999

In [56]:
a.max()

5.7000000000000002

In [57]:
a.mean()

3.0

In [58]:
a.std()

2.0079840636817816

In [59]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [60]:
a[4]

14

In [61]:
a[-1]

15

In [62]:
a[-6]

10

In [63]:
a[[1, 3, 4]]

array([11, 13, 14])

In [64]:
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [65]:
A[1, 2]

15

In [66]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [67]:
a[1:5]

array([11, 12, 13, 14])

In [68]:
a[1:5:2]

array([11, 13])

In [69]:
a[::2]

array([10, 12, 14])

In [70]:
a[:5:2]

array([10, 12, 14])

In [71]:
a[:5:]

array([10, 11, 12, 13, 14])

In [72]:
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [73]:
A[:, 0]

array([10, 13, 16])

In [74]:
A[0, :]

array([10, 11, 12])

In [75]:
A[0:2, 0:2]

array([[10, 11],
       [13, 14]])

In [76]:
A[[0, 2], 0:2]

array([[10, 11],
       [16, 17]])

In [77]:
for i in a:
    print(i)

10
11
12
13
14
15


In [78]:
for row in A:
    print(row)

[10 11 12]
[13 14 15]
[16 17 18]


In [79]:
for item in A.flat:
    print(item)

10
11
12
13
14
15
16
17
18


In [80]:
np.apply_along_axis(np.mean, axis=0, arr=A)

array([ 13.,  14.,  15.])

In [81]:
np.apply_along_axis(np.mean, axis=1, arr=A)

array([ 11.,  14.,  17.])

In [82]:
def foo(x):
    return x//2
np.apply_along_axis(foo, axis=1, arr=A)

array([[5, 5, 6],
       [6, 7, 7],
       [8, 8, 9]])

In [83]:
np.apply_along_axis(foo, axis=0, arr=A)

array([[5, 5, 6],
       [6, 7, 7],
       [8, 8, 9]])

In [84]:
A = np.random.random((4, 4))
A

array([[ 0.90243912,  0.57720568,  0.7606316 ,  0.54992019],
       [ 0.09667916,  0.10062766,  0.50863575,  0.73821901],
       [ 0.94934412,  0.51304658,  0.62235747,  0.90726485],
       [ 0.09132962,  0.81952976,  0.00138375,  0.3477299 ]])

In [85]:
A < 0.5

array([[False, False, False, False],
       [ True,  True, False, False],
       [False, False, False, False],
       [ True, False,  True,  True]], dtype=bool)

In [86]:
A[A < 0.5]

array([ 0.09667916,  0.10062766,  0.09132962,  0.00138375,  0.3477299 ])

In [87]:
a = np.random.random(12)
a

array([ 0.63150827,  0.2181745 ,  0.4460956 ,  0.99685201,  0.50023962,
        0.06016171,  0.60475523,  0.35892343,  0.03170966,  0.7872185 ,
        0.2632365 ,  0.05979131])

In [88]:
A = a.reshape(3, 4)
A

array([[ 0.63150827,  0.2181745 ,  0.4460956 ,  0.99685201],
       [ 0.50023962,  0.06016171,  0.60475523,  0.35892343],
       [ 0.03170966,  0.7872185 ,  0.2632365 ,  0.05979131]])

In [89]:
a.shape = (3, 4)
a

array([[ 0.63150827,  0.2181745 ,  0.4460956 ,  0.99685201],
       [ 0.50023962,  0.06016171,  0.60475523,  0.35892343],
       [ 0.03170966,  0.7872185 ,  0.2632365 ,  0.05979131]])

In [90]:
a = a.ravel()
a

array([ 0.63150827,  0.2181745 ,  0.4460956 ,  0.99685201,  0.50023962,
        0.06016171,  0.60475523,  0.35892343,  0.03170966,  0.7872185 ,
        0.2632365 ,  0.05979131])

In [91]:
a.shape = (12)
a

array([ 0.63150827,  0.2181745 ,  0.4460956 ,  0.99685201,  0.50023962,
        0.06016171,  0.60475523,  0.35892343,  0.03170966,  0.7872185 ,
        0.2632365 ,  0.05979131])

In [92]:
A.transpose()

array([[ 0.63150827,  0.50023962,  0.03170966],
       [ 0.2181745 ,  0.06016171,  0.7872185 ],
       [ 0.4460956 ,  0.60475523,  0.2632365 ],
       [ 0.99685201,  0.35892343,  0.05979131]])

In [93]:
A = np.ones((3, 3))
B = np.zeros((3, 3))
np.vstack((A, B))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [94]:
np.hstack((A, B))

array([[ 1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.]])

In [95]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [96]:
np.row_stack((a, b, c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [97]:
a.shape

(3,)

In [98]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [99]:
[B, C] = np.hsplit(A, 2)
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [100]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [101]:
[B, C] = np.vsplit(A, 2)
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [102]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
[A1, A2, A3] = np.split(A, [1, 3], axis=1)
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [104]:
A2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [105]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [106]:
[A1, A2, A3] = np.split(A, [1, 3], axis=0)
A1

array([[0, 1, 2, 3]])

In [107]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
A3

array([[12, 13, 14, 15]])

In [109]:
a = np.array([1, 2, 3, 4])
b = a
b

array([1, 2, 3, 4])

In [110]:
a[2] = 0
b

array([1, 2, 0, 4])

In [111]:
c = a[0:2]
c

array([1, 2])

In [112]:
a[0] = 0
c

array([0, 2])

In [113]:
a = np.array([1, 2, 3, 4])
c = a.copy()
c

array([1, 2, 3, 4])

In [114]:
a[0] = 0
c

array([1, 2, 3, 4])

In [115]:
a * b

array([ 0,  4,  0, 16])

In [116]:
A = np.arange(16).reshape(4, 4)
b = np.arange(4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [117]:
b

array([0, 1, 2, 3])

In [118]:
A + b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [119]:
m = np.arange(6).reshape(3, 1, 2)
n = np.arange(6).reshape(3, 2, 1)
m

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [120]:
n

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [121]:
m + n

array([[[ 0,  1],
        [ 1,  2]],

       [[ 4,  5],
        [ 5,  6]],

       [[ 8,  9],
        [ 9, 10]]])

In [122]:
data = np.random.random(12).reshape(4, 3)
data

array([[ 0.29976031,  0.93841996,  0.69250755],
       [ 0.92842561,  0.86505235,  0.58778743],
       [ 0.80065289,  0.1244734 ,  0.39763074],
       [ 0.14366218,  0.62366871,  0.44424515]])

In [123]:
np.save("saved_data", data)

In [124]:
load_data = np.load("saved_data.npy")
load_data

array([[ 0.29976031,  0.93841996,  0.69250755],
       [ 0.92842561,  0.86505235,  0.58778743],
       [ 0.80065289,  0.1244734 ,  0.39763074],
       [ 0.14366218,  0.62366871,  0.44424515]])

In [125]:
data = np.genfromtxt('data.csv', delimiter=",", names=True)
data

array([( 1.,  123.,  1.4,  23.), ( 2.,  110.,  0.5,  18.),
       ( 3.,  164.,  2.1,  19.)],
      dtype=[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value3', '<f8')])

In [126]:
data2 = np.genfromtxt("data2.csv", delimiter=",", names=True)
data2

array([( 1.,  123.,  1.4,  23.), ( 2.,  110.,  nan,  18.),
       ( 3.,   nan,  2.1,  19.)],
      dtype=[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value3', '<f8')])

In [127]:
data2["id"]

array([ 1.,  2.,  3.])